#数据库配置
spring:
  resources:
    add-mappings: true
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://10.90.72.126:8080/conan_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: conan
        password: '%zCM94bo'
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:

      url: jdbc:mysql://10.90.72.126:8080/conan_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
      password: La5Hha/wdY2u8iYSHN2JdPrUunJnu+bDoFr+fQhaNoyRXi6hxdAWJw7oatJn5LecK8N+Ls+mxLPbOwvtM8gD3Q==
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJgbbw4r01SO4o82/rXilIFLQGujU8xggtr+wTYgO2x0sdo1arGpQCXYsfQCXrGcvaIijUYmv+h/P9yoEvswciECAwEAAQ==


  redis:
    # 地址
    host: 10.90.71.149
    # 端口，默认为6379
    port: 6379
    # 密码
    password: test@123
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  kafka:
    bootstrap-servers: 10.90.72.126:9092
    consumer:
      group-id: conan-agent-test
  data:
    elasticsearch:
      #      cluster-name: elasticsearch
      #      cluster-nodes: 10.90.71.138:9300
      # cluster-name: xes_log_cluster_test
      # cluster-nodes: 10.90.71.158:9300,10.90.71.166:9300,10.90.71.44:9300
      cluster-name: xes_log_cluster_wg
      cluster-nodes: 10.20.34.105:9301
  jackson:
    time-zone: Asia/Shanghai    #或UTC
system:
  env: TEST
  redis:
    cacheTime: 14 # 录制redis数据的过期时间为14天
